<a href="https://colab.research.google.com/github/Aditya29051998/GenAI/blob/main/Master_GENAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Tokenization

In [ ]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
from nltk.tokenize import word_tokenize , sent_tokenize

In [ ]:
#Sample Text
txt = "Hello Mr. Smith, how are you doing today? The weather is great, and Python is awesome. The sky is pinkish-blue. You shouldn't eat cardboard."

In [ ]:
type(txt)

str

In [ ]:
word_tokenize(txt)

['Hello',
 'Mr.',
 'Smith',
 ',',
 'how',
 'are',
 'you',
 'doing',
 'today',
 '?',
 'The',
 'weather',
 'is',
 'great',
 ',',
 'and',
 'Python',
 'is',
 'awesome',
 '.',
 'The',
 'sky',
 'is',
 'pinkish-blue',
 '.',
 'You',
 'should',
 "n't",
 'eat',
 'cardboard',
 '.']

In [ ]:
txt2 = "Boy is good,Girl is good , Both boy and girl are good"

In [ ]:
word_tokenize(txt2)

['Boy',
 'is',
 'good',
 ',',
 'Girl',
 'is',
 'good',
 ',',
 'Both',
 'boy',
 'and',
 'girl',
 'are',
 'good']

In [ ]:
sent_tokenize(txt)

['Hello Mr. Smith, how are you doing today?',
 'The weather is great, and Python is awesome.',
 'The sky is pinkish-blue.',
 "You shouldn't eat cardboard."]

In [ ]:
sent_tokenize(txt2)

['Boy is good,Girl is good , Both boy and girl are good']

##Stop words Removal(The,is ,are,am) because it is not adding any inforamtion to out data

In [ ]:
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
#Input sentence
sentence = "This is an example showing off stop word filtration."

In [ ]:
#Tokenize the sentence
words = word_tokenize(sentence)

In [ ]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [ ]:
#Removing stop Words
stop_words = set(stopwords.words('english'))

In [ ]:
filtered_words = [word for word in words if word.lower() not in stop_words]

In [ ]:
filtered_words

['example', 'showing', 'stop', 'word', 'filtration', '.']

In [ ]:
filtered_sentence = ' '.join(filtered_words)

In [ ]:
print(filtered_sentence)

example showing stop word filtration .


##Stemming and Lemamatization

In [ ]:
from nltk.stem import PorterStemmer

In [ ]:
#initializing the stemmer
stemmer = PorterStemmer()

In [ ]:
Words = ['give','giving','given','gave']

In [ ]:
#Appling stemming technique
for word in Words:
  print(stemmer.stem(word))

give
give
given
gave


In [ ]:
#Lematizatin
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
#Intializing the Lemmatizer
lemmatizer = WordNetLemmatizer()

In [ ]:
words = ['cats','cacti','geese']

In [ ]:
for word in words:
  print(lemmatizer.lemmatize(word))

cat
cactus
goose


In [ ]:
word2 = ['give','giving','given','gave']

In [ ]:
for word in word2:
  print(lemmatizer.lemmatize(word))

give
giving
given
gave


##BAG OF WORDS


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
import pandas as pd

# Sample data
data = [
    ["Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...", "ham"],
    ["Ok lar... Joking wif u oni...", "ham"],
    ["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's", "spam"],
    ["U dun say so early hor... U c already then say...", "ham"],
    ["Nah I don't think he goes to usf, he lives around here though", "ham"],
    ["FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv", "spam"],
    ["Even my brother is not like to speak with me. They treat me like aids patent.", "ham"],
    ["As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune", "ham"],
    ["WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.", "spam"],
    ["Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030", "spam"]
]

# Create DataFrame
df = pd.DataFrame(data, columns=["v1", "v2"])

# Save to CSV
df.to_csv("spam_sample.csv", index=False)

In [ ]:
df = pd.read_csv("spam_sample.csv", encoding='latin-1')

In [ ]:
df

v1    v2
0  Go until jurong point, crazy.. Available only ...   ham
1                      Ok lar... Joking wif u oni...   ham
2  Free entry in 2 a wkly comp to win FA Cup fina...  spam
3  U dun say so early hor... U c already then say...   ham
4  Nah I don't think he goes to usf, he lives aro...   ham
5  FreeMsg Hey there darling it's been 3 week's n...  spam
6  Even my brother is not like to speak with me. ...   ham
7  As per your request 'Melle Melle (Oru Minnamin...   ham
8  WINNER!! As a valued network customer you have...  spam
9  Had your mobile 11 months or more? U R entitle...  spam

In [ ]:
df.v2.value_counts() # Replace 'Catagory' with 'v2' to access the correct column.


v2
ham     6
spam    4
Name: count, dtype: int64

In [ ]:
df['spam'] = df['v2'].apply(lambda x: 1 if x=='spam' else 0)

In [ ]:
df.head(5)

v1    v2  spam
0  Go until jurong point, crazy.. Available only ...   ham     0
1                      Ok lar... Joking wif u oni...   ham     0
2  Free entry in 2 a wkly comp to win FA Cup fina...  spam     1
3  U dun say so early hor... U c already then say...   ham     0
4  Nah I don't think he goes to usf, he lives aro...   ham     0

In [ ]:
#Train Test Split
X_train, X_test, y_train, y_test = train_test_split(df.v1, df.spam, test_size=0.25)

In [ ]:
X_train[:4]

0    Go until jurong point, crazy.. Available only ...
2    Free entry in 2 a wkly comp to win FA Cup fina...
9    Had your mobile 11 months or more? U R entitle...
7    As per your request 'Melle Melle (Oru Minnamin...
Name: v1, dtype: object

In [ ]:
from tkinter.constants import X
#Create bag of Words reprentaion using CountVectorizer
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
#X_train_cv = v.transform(X_test) # This line is causing the error. Remove it.
X_test_cv = v.transform(X_test)

In [ ]:
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 129 stored elements and shape (7, 117)>

In [ ]:
X_train_cv.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 2, 2, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 3, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

In [ ]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0])

In [ ]:
v.vocabulary_

{'go': 44,
 'until': 102,
 'jurong': 56,
 'point': 78,
 'crazy': 29,
 'available': 14,
 'only': 74,
 'in': 54,
 'bugis': 18,
 'great': 47,
 'world': 113,
 'la': 57,
 'buffet': 17,
 'cine': 24,
 'there': 96,
 'got': 46,
 'amore': 9,
 'wat': 107,
 'free': 40,
 'entry': 36,
 'wkly': 111,
 'comp': 27,
 'to': 100,
 'win': 109,
 'fa': 37,
 'cup': 30,
 'final': 38,
 'tkts': 99,
 '21st': 4,
 'may': 61,
 '2005': 3,
 'text': 93,
 '87121': 6,
 'receive': 83,
 'question': 80,
 'std': 90,
 'txt': 101,
 'rate': 81,
 'apply': 11,
 '08452810075over18': 1,
 'had': 48,
 'your': 116,
 'mobile': 64,
 '11': 2,
 'months': 66,
 'or': 75,
 'more': 67,
 'entitled': 35,
 'update': 104,
 'the': 94,
 'latest': 58,
 'colour': 26,
 'mobiles': 65,
 'with': 110,
 'camera': 22,
 'for': 39,
 'call': 19,
 'co': 25,
 'on': 73,
 '08002986030': 0,
 'as': 13,
 'per': 77,
 'request': 84,
 'melle': 62,
 'oru': 76,
 'minnaminunginte': 63,
 'nurungu': 71,
 'vettam': 106,
 'has': 49,
 'been': 16,
 'set': 87,
 'callertune': 21,
 

In [ ]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.where(X_train_np[0] != 0)

(array([72]),)

##ML MODEL

In [ ]:
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [ ]:
y_pred = model.predict(X_test_cv)

In [ ]:
print(accuracy_score(y_test, y_pred))

0.3333333333333333


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.33      1.00      0.50         1

    accuracy                           0.33         3
   macro avg       0.17      0.50      0.25         3
weighted avg       0.11      0.33      0.17         3



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
from sklearn.model_selection import KFold
cv = KFold(n_splits=5, shuffle=True, random_state=42)  # Replace 42 with any integer for reproducibility
scores = cross_val_score(rf_model, X_train_cv, y_train, cv=cv)

In [ ]:

 # 5-fold cross-validation

print("Cross-validation scores:", scores)
print("Average accuracy:", scores.mean())

Cross-validation scores: [0.5 0.5 0.  1.  1. ]
Average accuracy: 0.6


In [ ]:
#TF_IDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer


In [ ]:
corpus = [
    "This is the first document.",
    "This document is the second document.",
    "And this is the third one.",
    "Is this the first document?"
]

In [ ]:
v = TfidfVectorizer()
v.fit(corpus)
transformed_corpus = v.transform(corpus)

In [ ]:
print(v.vocabulary_)

{'this': 8, 'is': 3, 'the': 6, 'first': 2, 'document': 1, 'second': 5, 'and': 0, 'third': 7, 'one': 4}


In [ ]:
cv = CountVectorizer()
cv.fit(corpus)
transformed_corpus = cv.transform(corpus)
print(cv.vocabulary_)

{'this': 8, 'is': 3, 'the': 6, 'first': 2, 'document': 1, 'second': 5, 'and': 0, 'third': 7, 'one': 4}


In [ ]:
i = v.vocabulary_.get("second")
print(i)

5


In [ ]:
i = v.vocabulary_.get("one")
print(i)

4


In [ ]:
#Print idf of each word
df_idf = pd.DataFrame(v.idf_, index=v.get_feature_names_out(), columns=["idf_weights"])

